# Comentario generado automáticamente por Django que indica la versión del framework y la marca de tiempo de creación
# Generated by Django 6.1.1 on 2026-09-30 17:29

# Importa las clases base de migración y los tipos de campo del ORM de Django
from django.db import migrations, models


# Define la clase de la migración que hereda de la clase base 'Migration' de Django
class Migration(migrations.Migration):

    # Indica que esta es la primera migración de la app (crea el esquema base desde cero)
    initial = True

    # Lista de tuplas ('nombre_app', 'nombre_migracion') de las cuales depende esta migración antes de poder ejecutarse
    # Al estar vacía, no requiere que ninguna otra migración previa de esta app se haya corrido
    dependencies = [
    ]

    # Lista ordenada de operaciones DDL (Data Definition Language) que Django ejecutará en la base de datos
    operations = [
        # Operación para crear una nueva tabla en la base de datos
        migrations.CreateModel(
            # Nombre del modelo que originó la tabla (en BD se llamará comúnmente 'core_producto')
            name='Producto',
            
            # Lista de tuplas con el nombre de cada columna y su definición técnica a nivel de BD
            fields=[
                # Campo de clave primaria: BigAutoField genera un entero de 64 bits autonumérico (BIGSERIAL en PostgreSQL o INTEGER PRIMARY KEY AUTOINCREMENT en SQLite)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Columna VARCHAR(50) con una restricción de unicidad (UNIQUE constraint) e índice único en BD
                ('sku', models.CharField(help_text='Identificador único para el carrito (ej: b450, 99, 100)', max_length=50, unique=True)),
                
                # Columna VARCHAR(150) obligatoria (NOT NULL) para almacenar el nombre del producto
                ('nombre', models.CharField(max_length=150)),
                
                # Columna VARCHAR(50) con valor predeterminado 'Componentes'
                ('categoria', models.CharField(choices=[('Componentes', 'Componentes'), ('Audio', 'Audio'), ('Accesorios', 'Accesorios')], default='Componentes', max_length=50)),
                
                # Columna tipo TEXT sin límite estricto de caracteres para el detalle descriptivo
                ('descripcion', models.TextField()),
                
                # Columna de tipo INTEGER para almacenar el valor numérico del precio
                ('precio', models.IntegerField(help_text='Precio en pesos chilenos (sin puntos ni signos)')),
                
                # En la BD se almacena como un VARCHAR(100) con la ruta relativa del archivo dentro de MEDIA_ROOT/productos/
                ('imagen', models.ImageField(upload_to='productos/')),
                
                # Columna booleana (BOOLEAN/TINYINT) con valor por defecto True
                ('activo', models.BooleanField(default=True, help_text='Marcar si el producto está disponible para la venta')),
                
                # Columna TIMESTAMP/DATETIME que registra automáticamente la hora UTC de inserción en la BD
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            
            # Diccionario de opciones y metadatos de configuración transferidos desde el 'class Meta' del modelo
            options={
                'verbose_name': 'Producto',             # Etiqueta singular para la interfaz
                'verbose_name_plural': 'Productos',     # Etiqueta plural para la interfaz
                'ordering': ['-creado'],                # Orden SQL predeterminado al consultar este modelo (ORDER BY creado DESC)
            },
        ),
    ]
