# Generated by Django 6.1.1 on 2026-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Identificador único para el carrito (ej: b450, 99, 100)', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('Componentes', 'Componentes'), ('Audio', 'Audio'), ('Accesorios', 'Accesorios')], default='Componentes', max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(help_text='Precio en pesos chilenos (sin puntos ni signos)')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('activo', models.BooleanField(default=True, help_text='Marcar si el producto está disponible para la venta')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado'],
            },
        ),
    ]
