# Comentario automático generado por Django con la versión del framework y marca temporal de creación
# Generated by Django 6.1.1 on 2026-10-06 17:42

# Importa el módulo de validadores de Django (utilizado para serializar MinValueValidator y MaxValueValidator)
import django.core.validators

# Importa las directivas de eliminación en cascada y comportamiento referencial del ORM (models.deletion)
import django.db.models.deletion

# Importa las clases base de migración y los tipos de columna/campo del ORM
from django.db import migrations, models


# Define la clase de migración que hereda de la clase base 'Migration' de Django
class Migration(migrations.Migration):

    # Lista explícita de dependencias: esta migración solo se ejecutará si la migración '0001_initial' de la app 'core' ya fue aplicada
    dependencies = [
        ('core', '0001_initial'),
    ]

    # Lista de operaciones DDL que Django traducirá a sentencias SQL sobre la base de datos
    operations = [
        # Operación para crear la tabla correspondiente al modelo 'Valoracion' (típicamente 'core_valoracion' en BD)
        migrations.CreateModel(
            # Nombre del modelo que originó la entidad en la base de datos
            name='Valoracion',
            
            # Definición técnica de cada una de las columnas de la tabla
            fields=[
                # Clave primaria autoincremental de 64 bits (BigInt / BIGSERIAL)
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                # Columna de tipo INTEGER que almacena la calificación numérica con sus validadores de rango (1 a 5)
                ('puntuacion', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                
                # Columna de texto libre (tipo TEXT en SQL) para guardar la reseña u opinión
                ('comentario', models.TextField()),
                
                # Marca temporal automática (TIMESTAMP) que registra la fecha y hora UTC en el momento del INSERT
                ('creado', models.DateTimeField(auto_now_add=True)),
                
                # Clave foránea (FOREIGN KEY) que apunta al campo 'id' de la tabla 'core_producto':
                # - on_delete=CASCADE: si el producto referenciado se borra, la BD elimina automáticamente sus valoraciones asociadas
                # - related_name='valoraciones': nombre del descriptor inverso para acceder a estas reseñas desde la instancia de Producto
                # - to='core.producto': modelo de destino referenciado
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='core.producto')),
            ],
            
            # Opciones de metadatos del modelo aplicadas a nivel de framework
            options={
                'verbose_name': 'Valoración',             # Nombre en singular para la interfaz administrativa
                'verbose_name_plural': 'Valoraciones',     # Nombre en plural para la interfaz administrativa
                'ordering': ['-creado'],                # Orden SQL predeterminado al consultar (ORDER BY creado DESC)
            },
        ),
    ]
